version: '3'
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    entrypoint:  /bin/sh -c 'mkdir -p /etc/docker-gen/templates/  && wget -O /etc/docker-gen/templates/nginx.tmpl https://raw.githubusercontent.com/jwilder/nginx-proxy/985c46d8b56f2ee4652e9d75b49c128c14bee328/nginx.tmpl && /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf'
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  app:
    image: sammons/test-node-app
    ports:
      - 3000
    environment:
      VIRTUAL_HOST: example.io, app.example.io
      LETSENCRYPT_HOST: example.io, app.example.io
      LETSENCRYPT_EMAIL: you@whatever.io